[colors.primary]
background = "#0A4200"

[colors.normal]
green = "#45D42A"
red   = "#FF4242"

[colors.cursor]
cursor = "#B02615"

[font.normal]
family = "JetBrainsMono Nerd Font Mono"

[window]
startup_mode = "Maximized"
decorations  = "none"
